### ISSUE TITLE
SoftBody TODO list

### ISSUE THREAD

**Issue by dokthar** [Dokthar/jmonkeyengine#8]
- [x] check the GCollector for memory leak (native softbody are already released)
- [ ] complete current PhysicsSoftBody native binding
  - [x] <del>find a way to give access to Node, Face & Link (data structs that compose a btSoftBody )</del>
  - [x] add support for UV mapped mesh
  - [x] move util methods aways
  - [x] set vertices weight with a floatBuffer.
  - [x] Serialization
    - [x] Config Serialization
    - [x] Material Serialization
  - [x] fix margin collision distance
  - [x] add ropes constructor
  - [x] add Joint/Anchor support
    - [ ] make use of pivot 
  - [x] add debug for Joint <del>& Anchor</del>
  - [x] fix set & get rotation (not straight forward) should be fixed by #11 
- [x] SoftBodyControl
  - [x] update the mesh normal 
  - [x] update the vertices in local space (can be improved)
  - [x] Serialization (it doesn't store softbody "state") 
  - [x] clone for spatial
  - [x] setEnabled
  - [x] move the physics body to the correct position on creation
  - [x] rotate the physics body to the initial rotation on creation
- [x] <del>Check serialization of SoftBodyWorldInfo</del> (PhysicsAppState isn't serialized)
- [ ] manage the finalization of SoftBodyWorldInfo (using WeakReference)
- [x] Create a wiki page
